Repository babgroup/Dutchpay, pull requests merged in 2025-09, with the labels that each got.

#2 📖docs: update README
  README.md
Labels: documentation

#6 ✨ feat(restaurant): 초기 Restaurant API 및 Swagger + seed.sql 추가
  README.md
  backend/package-lock.json
  backend/package.json
  backend/seed.sql
  backend/src/app.controller.spec.ts
  backend/src/main.ts
  backend/src/restaurant/Type/current-food-rooms-response.type.ts
  backend/src/restaurant/Type/list-response.type.ts
  backend/src/restaurant/Type/user-list-response.type.ts
  backend/src/restaurant/dto/create-food-fare-room.dto.ts
  backend/src/restaurant/dto/create-restaurant.dto.ts
  backend/src/restaurant/dto/update-restaurant.dto.ts
  backend/src/restaurant/restaurant.controller.spec.ts
  backend/src/restaurant/restaurant.controller.ts
  backend/src/restaurant/restaurant.module.ts
  backend/src/restaurant/restaurant.service.spec.ts
  backend/src/restaurant/restaurant.service.ts
  backend/src/user/user.controller.spec.ts
  backend/src/user/user.service.spec.ts
Labels: documentation, enhancement

#7 ✨ feat(restaurant/leader): add Leader APIs for room details and progress update
  backend/src/restaurant/leader/Type/food-room-leader-response.type.ts
  backend/src/restaurant/leader/leader.controller.ts
  backend/src/restaurant/leader/leader.service.ts
  backend/src/restaurant/restaurant.module.ts
Labels: enhancement

#26 ✨ feat : Frontend temp commit to main
  frontend/.env.sample
  frontend/package.json
  frontend/public/angle-small-down.svg
  frontend/public/delivery.svg
  frontend/public/file.svg
  frontend/public/globe.svg
  frontend/public/home.svg
  frontend/public/next.svg
  frontend/public/user.svg
  frontend/public/vercel.svg
  frontend/public/window.svg
  frontend/src/app/components/BasicButton.tsx
  frontend/src/app/components/BottomNav.tsx
  frontend/src/app/components/BottomNavLayout.tsx
  frontend/src/app/components/Title.tsx
  frontend/src/app/delivery/(withTopHeader)/components/MemberCard.tsx
  frontend/src/app/delivery/(withTopHeader)/components/PartyInfoDiv.tsx
  frontend/src/app/delivery/(withTopHeader)/layout.tsx
  frontend/src/app/delivery/(withTopHeader)/leader/[id]/page.tsx
  frontend/src/app/delivery/(withTopHeader)/select-party-room/components/Dropdown.tsx
  frontend/src/app/delivery/(withTopHeader)/select-party-room/components/PartyTypeCard.tsx
  frontend/src/app/delivery/(withTopHeader)/select-party-room/page.tsx
  frontend/src/app/delivery/components/PartyPopup.tsx
  frontend/src/app/delivery/components/RoomListCard.tsx
  frontend/src/app/delivery/components/RoomListDiv.tsx
  frontend/src/app/delivery/components/SearchBar.tsx
  frontend/src/app/delivery/components/SortButton.tsx
  frontend/src/app/delivery/components/TopHeader.tsx
  frontend/src/app/delivery/components/plusButton.tsx
  frontend/src/app/delivery/page.tsx
  frontend/src/app/favicon.ico
  frontend/src/app/layout.tsx
  frontend/src/app/page.tsx
  frontend/src/app/user/page.tsx
  frontend/src/common/customFetch.ts
  frontend/src/common/formatDate.ts
  frontend/src/types/restaurant.ts
Labels: enhancement

#29 Feature/custom fetch
  frontend/src/app/delivery/(withTopHeader)/components/PartyInfoDiv.tsx
  frontend/src/common/customFetch.ts
Labels: enhancement

#35 ✨ feat : Feature/login page
  frontend/package-lock.json
  frontend/package.json
  frontend/public/babgroup.webp
  frontend/public/git.png
  frontend/src/app/(authPages)/components/AuthInput.tsx
  frontend/src/app/(authPages)/components/CopyRight.tsx
  frontend/src/app/(authPages)/components/LoginForm.tsx
  frontend/src/app/(authPages)/login/page.tsx
  frontend/src/app/components/BottomNav.tsx
  frontend/src/app/components/BottomNavLayout.tsx
  frontend/src/app/user/[id]/page.tsx
Labels: enhancement

#48 ✨feat : Implement /delivery/leader/:id page
  frontend/src/app/components/BasicButton.tsx
  frontend/src/app/delivery/(withTopHeader)/components/PartyButtonDiv.tsx
  frontend/src/app/delivery/(withTopHeader)/components/PartyContainer.tsx
  frontend/src/app/delivery/(withTopHeader)/components/PartyInfoDiv.tsx
  frontend/src/app/delivery/(withTopHeader)/leader/[id]/page.tsx
Labels: enhancement

#49 ✏️chore : Add routing to break-up-pary page
  frontend/src/app/delivery/(withTopHeader)/components/PartyContainer.tsx
  frontend/src/app/delivery/(withTopHeader)/leader/[id]/page.tsx
Labels: enhancement

#50 ✨ feat : Add break-up-party page
  frontend/src/app/delivery/breake-up-party/[roomId]/components/Toggle.tsx
  frontend/src/app/delivery/breake-up-party/[roomId]/page.tsx
Labels: enhancement

#51 ✨ feat : Add break-up-party page (fix previous commit)
  frontend/src/app/delivery/break-up-party/[id]/page.tsx
  frontend/src/app/delivery/break-up-party/components/BreakPartyContainer.tsx
Labels: enhancement
